### ISSUE TITLE
Run Demo getting Uncaught TypeError: _this.props.onClick is not a function

### ISSUE THREAD

**Issue by liudonghua123** [PieLabs/math-input#1]
I cloned the repo and run it like the instructions in README. But when I clicked any key on the keypad, nothing happened, and I opened the chrome-dev-tools and found some errors.

![image](https://user-images.githubusercontent.com/2276718/41147201-54ad945e-6b38-11e8-91af-dfbcaf039a94.png)

The console of shell shown no errors.

![image](https://user-images.githubusercontent.com/2276718/41147374-d215c420-6b38-11e8-9a37-5b24b13a7538.png)

**Comment by edeustace** [comment]
This repo has moved to pie-elements/pie-lib, try it there

**Comment by liudonghua123** [comment]
Thanks, I found it on https://github.com/PieElements/pie-libs/tree/master/packages/editable-html.
